name: "depth_anything_v2"
backend: "pytorch"
max_batch_size: 5

input [
  {
    name: "INPUT__0"
    data_type: TYPE_FP32
    dims: [ 3, 252, 252 ]
  }
]

output [
  {
    name: "OUTPUT__0"
    data_type: TYPE_FP32
    dims: [ 252, 252 ]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]

dynamic_batching {
  preferred_batch_size: 5 
  max_queue_delay_microseconds: 2000
}
